// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: internal/proto/enumerations.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EyeColour int32

const (
	EyeColour_EYE_COLOUR_UNSPECIFIED EyeColour = 0
	EyeColour_EYE_COLOUR_GREEN       EyeColour = 1
	EyeColour_EYE_COLOUR_BLUE        EyeColour = 2
	EyeColour_EYE_COLOUR_BROWN       EyeColour = 3
)

// Enum value maps for EyeColour.
var (
	EyeColour_name = map[int32]string{
		0: "EYE_COLOUR_UNSPECIFIED",
		1: "EYE_COLOUR_GREEN",
		2: "EYE_COLOUR_BLUE",
		3: "EYE_COLOUR_BROWN",
	}
	EyeColour_value = map[string]int32{
		"EYE_COLOUR_UNSPECIFIED": 0,
		"EYE_COLOUR_GREEN":       1,
		"EYE_COLOUR_BLUE":        2,
		"EYE_COLOUR_BROWN":       3,
	}
)

func (x EyeColour) Enum() *EyeColour {
	p := new(EyeColour)
	*p = x
	return p
}

func (x EyeColour) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EyeColour) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_proto_enumerations_proto_enumTypes[0].Descriptor()
}

func (EyeColour) Type() protoreflect.EnumType {
	return &file_internal_proto_enumerations_proto_enumTypes[0]
}

func (x EyeColour) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EyeColour.Descriptor instead.
func (EyeColour) EnumDescriptor() ([]byte, []int) {
	return file_internal_proto_enumerations_proto_rawDescGZIP(), []int{0}
}

type Enumeration struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EyeColour EyeColour `protobuf:"varint,1,opt,name=eye_colour,json=eyeColour,proto3,enum=example.enumerations.EyeColour" json:"eye_colour,omitempty"`
}

func (x *Enumeration) Reset() {
	*x = Enumeration{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_enumerations_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Enumeration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Enumeration) ProtoMessage() {}

func (x *Enumeration) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_enumerations_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Enumeration.ProtoReflect.Descriptor instead.
func (*Enumeration) Descriptor() ([]byte, []int) {
	return file_internal_proto_enumerations_proto_rawDescGZIP(), []int{0}
}

func (x *Enumeration) GetEyeColour() EyeColour {
	if x != nil {
		return x.EyeColour
	}
	return EyeColour_EYE_COLOUR_UNSPECIFIED
}

var File_internal_proto_enumerations_proto protoreflect.FileDescriptor

var file_internal_proto_enumerations_proto_rawDesc = []byte{
	0x0a, 0x21, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x65, 0x6e, 0x75, 0x6d, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x14, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x65, 0x6e, 0x75,
	0x6d, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x4d, 0x0a, 0x0b, 0x45, 0x6e, 0x75,
	0x6d, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x3e, 0x0a, 0x0a, 0x65, 0x79, 0x65, 0x5f,
	0x63, 0x6f, 0x6c, 0x6f, 0x75, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1f, 0x2e, 0x65,
	0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x65, 0x6e, 0x75, 0x6d, 0x65, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x2e, 0x45, 0x79, 0x65, 0x43, 0x6f, 0x6c, 0x6f, 0x75, 0x72, 0x52, 0x09, 0x65,
	0x79, 0x65, 0x43, 0x6f, 0x6c, 0x6f, 0x75, 0x72, 0x2a, 0x68, 0x0a, 0x09, 0x45, 0x79, 0x65, 0x43,
	0x6f, 0x6c, 0x6f, 0x75, 0x72, 0x12, 0x1a, 0x0a, 0x16, 0x45, 0x59, 0x45, 0x5f, 0x43, 0x4f, 0x4c,
	0x4f, 0x55, 0x52, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10,
	0x00, 0x12, 0x14, 0x0a, 0x10, 0x45, 0x59, 0x45, 0x5f, 0x43, 0x4f, 0x4c, 0x4f, 0x55, 0x52, 0x5f,
	0x47, 0x52, 0x45, 0x45, 0x4e, 0x10, 0x01, 0x12, 0x13, 0x0a, 0x0f, 0x45, 0x59, 0x45, 0x5f, 0x43,
	0x4f, 0x4c, 0x4f, 0x55, 0x52, 0x5f, 0x42, 0x4c, 0x55, 0x45, 0x10, 0x02, 0x12, 0x14, 0x0a, 0x10,
	0x45, 0x59, 0x45, 0x5f, 0x43, 0x4f, 0x4c, 0x4f, 0x55, 0x52, 0x5f, 0x42, 0x52, 0x4f, 0x57, 0x4e,
	0x10, 0x03, 0x42, 0x2d, 0x5a, 0x2b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x73, 0x61, 0x6d, 0x6d, 0x65, 0x34, 0x6c, 0x69, 0x66, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2d, 0x67, 0x6f, 0x2d, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_proto_enumerations_proto_rawDescOnce sync.Once
	file_internal_proto_enumerations_proto_rawDescData = file_internal_proto_enumerations_proto_rawDesc
)

func file_internal_proto_enumerations_proto_rawDescGZIP() []byte {
	file_internal_proto_enumerations_proto_rawDescOnce.Do(func() {
		file_internal_proto_enumerations_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_proto_enumerations_proto_rawDescData)
	})
	return file_internal_proto_enumerations_proto_rawDescData
}

var file_internal_proto_enumerations_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_proto_enumerations_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_internal_proto_enumerations_proto_goTypes = []interface{}{
	(EyeColour)(0),      // 0: example.enumerations.EyeColour
	(*Enumeration)(nil), // 1: example.enumerations.Enumeration
}
var file_internal_proto_enumerations_proto_depIdxs = []int32{
	0, // 0: example.enumerations.Enumeration.eye_colour:type_name -> example.enumerations.EyeColour
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_proto_enumerations_proto_init() }
func file_internal_proto_enumerations_proto_init() {
	if File_internal_proto_enumerations_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_proto_enumerations_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Enumeration); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_proto_enumerations_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_proto_enumerations_proto_goTypes,
		DependencyIndexes: file_internal_proto_enumerations_proto_depIdxs,
		EnumInfos:         file_internal_proto_enumerations_proto_enumTypes,
		MessageInfos:      file_internal_proto_enumerations_proto_msgTypes,
	}.Build()
	File_internal_proto_enumerations_proto = out.File
	file_internal_proto_enumerations_proto_rawDesc = nil
	file_internal_proto_enumerations_proto_goTypes = nil
	file_internal_proto_enumerations_proto_depIdxs = nil
}
